wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.6
    framework: huggingface
    huggingface_version: 4.44.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1724309563
    t:
      1:
      - 1
      - 5
      - 10
      - 11
      - 41
      - 48
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 10
      - 11
      - 41
      - 48
      - 49
      - 53
      - 55
      3:
      - 13
      - 23
      4: 3.10.12
      5: 0.17.6
      6: 4.44.0
      8:
      - 5
      13: linux-x86_64
